// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Mhill888
// Levels and setups are an interpretation of the 8020 strategy © 8020 Trading Pit https://8020prop.com
// All indications should be traded with the individual discretion of the user
//@version=6

indicator("MHT 8020", overlay=true)

// variables

emaLen = input.int(50, minval=1, step=10, title="EMA Length")
trLen1 = input.int(3,"Top Range length (min)", minval = 1, maxval = 100, step = 1)
trLen10 = input.int(10,"Bottom Range length (min)", minval = 1, maxval = 100, step = 1)
eightyTwentyColor = input.color(color.silver, "8020 Colour")
levelsColor = input.color(color.new(color.silver,transp = 67), "Levels Colour")
lineStyle = input.string('Solid', 'Level Line Style', ['Solid', 'Dashed', 'Dotted'])
lineStyleMA = input.string('Dotted', 'MA Line Style', ['Solid', 'Dashed', 'Dotted'])
colr=color.rgb(255, 255, 255, 25)
colg=color.rgb(255, 255, 255, 25)
labelIndent = input.int(5,'Label Indent')

repair = low==open?1:0
repairS = high==open?1:0

trLen1Str = str.tostring((trLen1), '#')
tr1H = request.security(syminfo.tickerid,"1",high)
tr1L = request.security(syminfo.tickerid,"1",low)
float minuteRange = math.abs(tr1H - tr1L)
float threeMinuteRange = 0

for i = 0 to (trLen1 -1)
    threeMinuteRange := threeMinuteRange + minuteRange[i]
trStr = str.tostring((threeMinuteRange), format.mintick)

trLen10Str = str.tostring((trLen10), '#')
tr10H = request.security(syminfo.tickerid,"1",ta.highest(trLen10))
tr10L = request.security(syminfo.tickerid,"1",ta.lowest(trLen10))
tr10 = math.abs(tr10H - tr10L)
trStr10 = str.tostring(tr10, format.mintick)
tr10Ema = ta.ema(tr10,21)
tr1Ema = ta.ema(minuteRange,21)
trEma = (tr10Ema + tr1Ema) /2

mistress = math.abs(open - close[1]) > 1 ? open : 0


var float onehundred = na
var label labeltr = na
var label label0 = na
var label label1 = na
var label label2 = na
var label label3 = na
var label label4 = na
var label label5 = na
var label label6 = na
var label label7 = na
var label label8 = na
var label label9 = na
var label label10 = na
var label label11 = na
var label label12 = na
var label label13 = na

// find nearest 100 level (rounded down)

RoundToHundredsDown(value) => math.floor(value / 100.0) * 100
onehundred := RoundToHundredsDown(open)
  
lineStyle(x) => switch x
    'Solid' => line.style_solid
    'Dashed' => line.style_dashed
    'Dotted' => line.style_dotted

lineStylePlot = switch lineStyleMA
    'Solid' => plot.linestyle_solid
    'Dashed' => plot.linestyle_dashed
    'Dotted' => plot.linestyle_dotted
    => plot.linestyle_solid

// draw lines

arr8020 = array.new_float(0)

array.push(arr8020, (onehundred - 320))
array.push(arr8020, (onehundred - 280))
array.push(arr8020, (onehundred - 220))
array.push(arr8020, (onehundred - 180))
array.push(arr8020, (onehundred - 120))
array.push(arr8020, (onehundred - 80))
array.push(arr8020, (onehundred - 20))
array.push(arr8020, (onehundred + 20))
array.push(arr8020, (onehundred + 80))
array.push(arr8020, (onehundred + 120))
array.push(arr8020, (onehundred + 180))
array.push(arr8020, (onehundred + 220))
array.push(arr8020, (onehundred + 280))
array.push(arr8020, (onehundred + 320))

for [index, value] in line.all
    line.delete(value) 

line.new(bar_index, (array.get(arr8020,0)), bar_index, (array.get(arr8020,0)), color = levelsColor, style = lineStyle(lineStyle))
line.new(bar_index, (array.get(arr8020,1)), bar_index, (array.get(arr8020,1)), color = levelsColor, style = lineStyle(lineStyle))
line.new(bar_index, (array.get(arr8020,2)), bar_index, (array.get(arr8020,2)), color = levelsColor, style = lineStyle(lineStyle))
line.new(bar_index, (array.get(arr8020,3)), bar_index, (array.get(arr8020,3)), color = levelsColor, style = lineStyle(lineStyle))
line.new(bar_index, (array.get(arr8020,4)), bar_index, (array.get(arr8020,4)), color = levelsColor, style = lineStyle(lineStyle))
line.new(bar_index, (array.get(arr8020,5)), bar_index, (array.get(arr8020,5)), color = levelsColor, style = lineStyle(lineStyle))
line.new(bar_index, (array.get(arr8020,6)), bar_index, (array.get(arr8020,6)), color = levelsColor, style = lineStyle(lineStyle))
line.new(bar_index, (array.get(arr8020,7)), bar_index, (array.get(arr8020,7)), color = levelsColor, style = lineStyle(lineStyle))
line.new(bar_index, (array.get(arr8020,8)), bar_index, (array.get(arr8020,8)), color = levelsColor, style = lineStyle(lineStyle))
line.new(bar_index, (array.get(arr8020,9)), bar_index, (array.get(arr8020,9)), color = levelsColor, style = lineStyle(lineStyle))
line.new(bar_index, (array.get(arr8020,10)), bar_index, (array.get(arr8020,10)), color = levelsColor, style = lineStyle(lineStyle))
line.new(bar_index, (array.get(arr8020,11)), bar_index, (array.get(arr8020,11)), color = levelsColor, style = lineStyle(lineStyle))
line.new(bar_index, (array.get(arr8020,12)), bar_index, (array.get(arr8020,12)), color = levelsColor, style = lineStyle(lineStyle))
line.new(bar_index, (array.get(arr8020,13)), bar_index, (array.get(arr8020,13)), color = levelsColor, style = lineStyle(lineStyle))

// set the left and right x coordinates of all of the lines

for [index, value] in line.all
    line.set_x1(value, bar_index +1)
    line.set_x2(value, bar_index + labelIndent)

// labels

label.delete(labeltr)
labeltr := label.new(bar_index + (labelIndent + 10), open, text = trLen1Str + " min ∑range " + trStr + "\n" + trLen10Str + " min range " + trStr10, style = label.style_label_center, textcolor = color.white, text_formatting = text.format_bold)
label.set_color(labeltr,color.navy)

label.delete(label0)
label0 := label.new(bar_index + 3, (array.get(arr8020,0)), '80', style = label.style_none, textcolor = eightyTwentyColor, text_formatting = text.format_bold)

label.delete(label1)
label1 := label.new(bar_index + 3, (array.get(arr8020,1)), '20', style = label.style_none, textcolor = eightyTwentyColor, text_formatting = text.format_bold)

label.delete(label2)
label2 := label.new(bar_index + 3, (array.get(arr8020,2)), '80', style = label.style_none, textcolor = eightyTwentyColor, text_formatting = text.format_bold)

label.delete(label3)
label3 := label.new(bar_index + 3, (array.get(arr8020,3)), '20', style = label.style_none, textcolor = eightyTwentyColor, text_formatting = text.format_bold)

label.delete(label4)
label4 := label.new(bar_index + 3, (array.get(arr8020,4)), '80', style = label.style_none, textcolor = eightyTwentyColor, text_formatting = text.format_bold)

label.delete(label5)
label5 := label.new(bar_index + 3, (array.get(arr8020,5)), '20', style = label.style_none, textcolor = eightyTwentyColor, text_formatting = text.format_bold)
  
label.delete(label6)
label6 := label.new(bar_index + 3, (array.get(arr8020,6)), '80', style = label.style_none, textcolor = eightyTwentyColor, text_formatting = text.format_bold)

label.delete(label7)
label7 := label.new(bar_index + 3, (array.get(arr8020,7)), '20', style = label.style_none, textcolor = eightyTwentyColor, text_formatting = text.format_bold)

label.delete(label8)
label8 := label.new(bar_index + 3, (array.get(arr8020,8)), '80', style = label.style_none, textcolor = eightyTwentyColor, text_formatting = text.format_bold)

label.delete(label9)
label9 := label.new(bar_index + 3, (array.get(arr8020,9)), '20', style = label.style_none, textcolor = eightyTwentyColor, text_formatting = text.format_bold)

label.delete(label10)
label10 := label.new(bar_index + 3, (array.get(arr8020,10)), '80', style = label.style_none, textcolor = eightyTwentyColor, text_formatting = text.format_bold)

label.delete(label11)
label11 := label.new(bar_index + 3, (array.get(arr8020,11)), '20', style = label.style_none, textcolor = eightyTwentyColor, text_formatting = text.format_bold)
 
label.delete(label12)
label12 := label.new(bar_index + 3, (array.get(arr8020,12)), '80', style = label.style_none, textcolor = eightyTwentyColor, text_formatting = text.format_bold)

label.delete(label13)
label13 := label.new(bar_index + 3, (array.get(arr8020,13)), '20', style = label.style_none, textcolor = eightyTwentyColor, text_formatting = text.format_bold)
 
//moving average outputs

arrMa = array.new_float(0)

array.push(arrMa, 1)
array.push(arrMa, 2)
array.push(arrMa, 3)
array.push(arrMa, 4)
array.push(arrMa, 5)

outa = ta.ema(close, emaLen)

//moving average plots

col=open>outa ? #00ff00 : #ff0000  
plot(outa, color=col, linewidth=2, offset = 0)
plot((outa - (ta.atr(10) * (array.get(arrMa,0)))), color=colr, linewidth=1, style = plot.style_line, offset=0, linestyle = lineStylePlot)
plot((outa - (ta.atr(10) * (array.get(arrMa,1)))), color=colr, linewidth=1, style = plot.style_line, offset=0, linestyle = lineStylePlot)
plot((outa - (ta.atr(10) * (array.get(arrMa,2)))), color=colr, linewidth=1, style = plot.style_line, offset=0, linestyle = lineStylePlot)
plot((outa - (ta.atr(10) * (array.get(arrMa,3)))), color=colr, linewidth=1, style = plot.style_line, offset=0, linestyle = lineStylePlot)
plot((outa - (ta.atr(10) * (array.get(arrMa,4)))), color=colr, linewidth=1, style = plot.style_line, offset=0, linestyle = lineStylePlot)
plot((outa + (ta.atr(10) * (array.get(arrMa,0)))), color=colg, linewidth=1, style = plot.style_line, offset=0, linestyle = lineStylePlot)
plot((outa + (ta.atr(10) * (array.get(arrMa,1)))), color=colg, linewidth=1, style = plot.style_line, offset=0, linestyle = lineStylePlot)
plot((outa + (ta.atr(10) * (array.get(arrMa,2)))), color=colg, linewidth=1, style = plot.style_line, offset=0, linestyle = lineStylePlot)
plot((outa + (ta.atr(10) * (array.get(arrMa,3)))), color=colg, linewidth=1, style = plot.style_line, offset=0, linestyle = lineStylePlot)
plot((outa + (ta.atr(10) * (array.get(arrMa,4)))), color=colg, linewidth=1, style = plot.style_line, offset=0, linestyle = lineStylePlot)

// 8020 plots 

plotshape(repair,"Repair",shape.xcross,location.absolute,color.white)
plotshape(repairS,"RepairS",shape.xcross,location.absolute,color.white)
plotshape(mistress,"Mistress",style = shape.xcross,location = location.absolute,color = color.white, size = size.auto, force_overlay = true)